version: '3'  # The version of Docker Compose configuration being used

services:
  db:  # Container to run MySQL database
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql  # Mounting the volume to persist database data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:  # Container to run WordPress and connect to the above container
    image: wordpress:latest
    depends_on:
      - db  # Specify that the WordPress container depends on the db container
    ports:
      - "8081:80"  # Mapping host port 8080 to container port 80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: {}  # Creating a named volume for MySQL data persistence
